"""Model-facing computer-use runtime primitives."""

from .contracts import (
    ActionExecution,
    BCoreReview,
    BatchExecution,
    BatchPreconditions,
    BatchSpec,
    DeceptionGrade,
    LobeBProfile,
    LobeDecision,
    ParallelBranchReport,
    ParallelBranchSpec,
    ParallelRuntimeReport,
    ParallelSplitPlan,
    PredictedState,
    RiskClass,
    RuntimeObservation,
    RuntimeReport,
    ScreenAssessment,
)
from .runtime import (
    DualLobeRuntime,
    LobeA,
    LobeB,
    DesktopAdapter,
    ParallelDualLobeRuntime,
    ScreenAwareDualLobeRuntime,
    ScreenAwareLobeB,
    SingleLoopRuntime,
    StaleBatch,
)

__all__ = [
    "ActionExecution",
    "BCoreReview",
    "BatchExecution",
    "BatchPreconditions",
    "BatchSpec",
    "DeceptionGrade",
    "DesktopAdapter",
    "DualLobeRuntime",
    "LobeA",
    "LobeBProfile",
    "LobeB",
    "LobeDecision",
    "ParallelBranchReport",
    "ParallelBranchSpec",
    "ParallelDualLobeRuntime",
    "ParallelRuntimeReport",
    "ParallelSplitPlan",
    "PredictedState",
    "RiskClass",
    "RuntimeObservation",
    "RuntimeReport",
    "ScreenAssessment",
    "ScreenAwareDualLobeRuntime",
    "ScreenAwareLobeB",
    "SingleLoopRuntime",
    "StaleBatch",
]
